# Configuração de Build
[build]
  command = "echo 'Build concluído com sucesso'"
    publish = "."
      functions = "netlify/functions"

      # Configurações de Functions
      [functions]
        directory = "netlify/functions"
          node_bundler = "esbuild"

          # Configuração de ambiente Node
          [build.environment]
            NODE_VERSION = "18"
              NPM_VERSION = "9"

              # Redirects e Rewrites
              [[redirects]]
                from = "/api/*"
                  to = "/.netlify/functions/:splat"
                    status = 200
                      force = true

                      [[redirects]]
                        from = "/*"
                          to = "/index.html"
                            status = 200

                            # Headers de segurança e CORS
                            [[headers]]
                              for = "/*"
                                [headers.values]
                                    Access-Control-Allow-Origin = "*"
                                        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
                                            Access-Control-Allow-Headers = "Content-Type, Authorization"
                                                X-Frame-Options = "DENY"
                                                    X-Content-Type-Options = "nosniff"
                                                        X-XSS-Protection = "1; mode=block"
                                                            Referrer-Policy = "no-referrer-when-downgrade"

                                                            [[headers]]
                                                              for = "/.netlify/functions/*"
                                                                [headers.values]
                                                                    Access-Control-Allow-Origin = "*"
                                                                        Access-Control-Allow-Methods = "GET, POST, OPTIONS"
                                                                            Access-Control-Allow-Headers = "Content-Type"
                                                                                Cache-Control = "no-cache, no-store, must-revalidate"

                                                                                # Configurações de cache
                                                                                [[headers]]
                                                                                  for = "/*.js"
                                                                                    [headers.values]
                                                                                        Cache-Control = "public, max-age=31536000, immutable"

                                                                                        [[headers]]
                                                                                          for = "/*.css"
                                                                                            [headers.values]
                                                                                                Cache-Control = "public, max-age=31536000, immutable"

                                                                                                [[headers]]
                                                                                                  for = "/*.html"
                                                                                                    [headers.values]
                                                                                                        Cache-Control = "public, max-age=0, must-revalidate"

                                                                                                        # Configurações de contexto
                                                                                                        [context.production]
                                                                                                          command = "echo 'Deploy de produção'"
                                                                                                            
                                                                                                            [context.deploy-preview]
                                                                                                              command = "echo 'Deploy de preview'"

                                                                                                              [context.branch-deploy]
                                                                                                                command = "echo 'Deploy de branch'"

                                                                                                                # Configurações de desenvolvimento local
                                                                                                                [dev]
                                                                                                                  command = "echo 'Servidor local iniciado'"
                                                                                                                    port = 8888
                                                                                                                      targetPort = 8888
                                                                                                                        publish = "."
                                                                                                                          autoLaunch = true